"""Fix relationship conflict

Revision ID: 13c81112e7ff
Revises: 6fd3e0d8c51c
Create Date: 2025-10-07 12:26:31.217104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c81112e7ff'
down_revision = '6fd3e0d8c51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assignee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['assignee_id'], ['id'])

    # ### end Alembic commands ###
