"""baseline

Revision ID: 626db276b5a9
Revises: 
Create Date: 2026-01-19 08:39:40.203486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626db276b5a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_connection')
    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.alter_column('from_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('to_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('workspace_id')
        batch_op.drop_column('portfolio_id')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_task_assigned_by', 'user', ['assigned_by_id'], ['id'])
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pro', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('plan', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subscription_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sub_expiry', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('job_title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('team',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('initials')
        batch_op.drop_column('avatar_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_color', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('initials', sa.VARCHAR(length=5), nullable=True))
        batch_op.alter_column('team',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('job_title',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('sub_expiry')
        batch_op.drop_column('subscription_id')
        batch_op.drop_column('plan')
        batch_op.drop_column('is_pro')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('workspace_id', sa.INTEGER(), nullable=True))
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('connection', schema=None) as batch_op:
        batch_op.alter_column('to_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('from_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('_alembic_tmp_connection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('from_user_id', sa.INTEGER(), nullable=True),
    sa.Column('to_user_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
